Description: Creates a basic DynamoDB Table
Parameters:
    pOwner:
        Description: Owner's Name
        AllowedPattern: ^([A-Za-z0-9 ]*)?$
        Type: String
    pEmail:
        Description: Owner's e-Mail'
        AllowedPattern: ^([A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,3})?$
        Type: String
    pResourceName:
        Description: Name for the Resource
        AllowedPattern: ^([A-Za-z0-9]*)?$
        Type: String

Resources:
    rDynamoDBMainTable:
        Type: "AWS::DynamoDB::Table"
        Properties:
            AttributeDefinitions: 
            - 
                AttributeName: "dnc-name"
                AttributeType: "S"
            KeySchema: 
            - 
                AttributeName: "dnc-name"
                KeyType: "HASH"
            ProvisionedThroughput: 
                ReadCapacityUnits: "5"
                WriteCapacityUnits: "5"
            TableName: "DNCMainTable"
            Tags:
                - Key: Owner
                  Value: !Ref pOwner
                - Key: Email
                  Value: !Ref pEmail
                - Key: ResourceName
                  Value: !Sub ${pResourceName}-DynamoDBMainTable-${AWS::Region}-${AWS::AccountId}

    rDynamoDBServiceTable:
        Type: "AWS::DynamoDB::Table"
        Properties:
            AttributeDefinitions: 
            - 
                AttributeName: "service-name"
                AttributeType: "S"
            KeySchema: 
            - 
                AttributeName: "service-name"
                KeyType: "HASH"
            ProvisionedThroughput: 
                ReadCapacityUnits: "5"
                WriteCapacityUnits: "5"
            TableName: "DNCServiceTable"
            Tags:
                - Key: Owner
                  Value: !Ref pOwner
                - Key: Email
                  Value: !Ref pEmail
                - Key: ResourceName
                  Value: !Sub ${pResourceName}-DynamoDBServiceTable-${AWS::Region}-${AWS::AccountId}
Outputs:
    oDynamoDBMainTable:
        Value: !Ref rDynamoDBMainTable
        Description: DynamoDB Main Table
    oDynamoDBServiceTable:
        Value: !Ref rDynamoDBServiceTable
        Description: DynamoDB Service Table